# Generated by Django 3.1.6 on 2021-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0002_auto_20210208_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomemember',
            name='photo',
            field=models.ImageField(blank=True, default='default_member.jpg', upload_to='members_photo'),
        ),
    ]
