# Generated by Django 3.1.6 on 2021-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0003_becomemember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
