# Generated by Django 3.1.6 on 2021-02-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0004_auto_20210209_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSuggestions',
        ),
    ]
