# Generated by Django 3.1.6 on 2021-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0005_delete_postsuggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio_content',
            field=models.FileField(blank=True, help_text='select audio content', upload_to='post_audio_files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True, help_text="You can leave this field blank if you don't need to add text"),
        ),
    ]
