# Generated by Django 3.1.6 on 2021-02-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0006_auto_20210214_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
