# Generated by Django 3.1.6 on 2021-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0007_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomemember',
            name='photo',
        ),
    ]
