# Generated by Django 3.1.6 on 2021-02-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0008_remove_becomemember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomemember',
            name='phone',
        ),
    ]
