# Generated by Django 3.1.6 on 2021-03-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0009_remove_becomemember_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_of_comment',
            new_name='date_posted',
        ),
    ]
