# Generated by Django 3.1.6 on 2021-03-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0010_auto_20210301_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='date_of_comment',
        ),
    ]
