# Generated by Django 3.1.6 on 2021-03-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0011_auto_20210301_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
