# Generated by Django 3.1.6 on 2021-03-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0012_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=150),
        ),
    ]
