# Generated by Django 3.1.6 on 2021-03-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0013_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
