# Generated by Django 3.1.6 on 2021-03-02 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0014_remove_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_of_comment',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_comment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
