# Generated by Django 3.1.6 on 2021-03-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0015_auto_20210302_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
    ]
