# Generated by Django 3.1.6 on 2021-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0016_remove_post_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
