# Generated by Django 3.1.6 on 2021-03-03 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0017_remove_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('testimony', models.TextField()),
                ('date_of_testimony', models.DateField(default=django.utils.timezone.now)),
                ('time_of_testimony', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
