# Generated by Django 3.1.6 on 2021-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0018_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_of_comment',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='time_of_testimony',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_comment',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='date_of_testimony',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
