# Generated by Django 3.1.6 on 2021-03-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0022_becomemember_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='views',
        ),
        migrations.AlterField(
            model_name='thought',
            name='bible_quotations',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
