# Generated by Django 3.1.6 on 2021-03-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4thought', '0024_answers_message_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomemember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='email',
        ),
    ]
